# Generated by Django 3.2.5 on 2021-07-27 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('position', models.CharField(choices=[('customer', 'customer'), ('owner', 'owner'), ('admin', 'admin')], default='customer', max_length=30)),
                ('fullname', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='userimages')),
                ('username', models.CharField(max_length=30)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=30)),
                ('price_for_udults', models.FloatField()),
                ('price_for_childs', models.FloatField(blank=True, null=True)),
                ('occupancy_for_udults', models.IntegerField()),
                ('occupancy_for_childs', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'active'), ('open', 'open')], max_length=30)),
                ('total_booking', models.IntegerField(blank=True, null=True)),
                ('active_booking', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('owner', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='customers.myuser')),
                ('name', models.CharField(max_length=30)),
                ('hotel_phone', models.IntegerField()),
                ('hotel_address', models.CharField(max_length=50)),
                ('star', models.IntegerField()),
                ('hotel_image', models.ImageField(upload_to='hotel-images')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active'), ('rejected', 'rejected'), ('delete', 'delete')], default='pending', max_length=30)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.room')),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='customers.hotel'),
        ),
    ]
