# Generated by Django 3.2.5 on 2021-07-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_hotel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_image',
            field=models.ImageField(blank=True, null=True, upload_to='room-images'),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('active', 'active'), ('open', 'open')], default='open', max_length=30),
        ),
    ]
