# Generated by Django 3.2.5 on 2021-07-28 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20210728_0715'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='occupancy_for_childs',
            new_name='occupancy_for_child',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='occupancy_for_udults',
            new_name='occupancy_for_udult',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price_for_udults',
            new_name='price_for_adult',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='price_for_childs',
            new_name='price_for_child',
        ),
    ]
