# Generated by Django 3.2.5 on 2021-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_rename_occupancy_for_udult_room_occupancy_for_adult'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
