# Generated by Django 3.2.5 on 2021-07-29 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_hotel_min'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotel',
            name='min',
        ),
    ]
