# Generated by Django 3.2.5 on 2021-07-30 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='number_of_adult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='number_of_child',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
