# Generated by Django 3.2.5 on 2021-07-30 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0010_auto_20210730_0646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('booked', 'booked'), ('rejected', 'rejected'), ('complete', 'complete')], default='requested', max_length=30),
        ),
    ]
