# Generated by Django 3.2.5 on 2021-07-30 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('requested', 'requested'), ('booked', 'booked'), ('rejected', 'rejected'), ('completed', 'completed')], default='requested', max_length=30),
        ),
    ]
