# Generated by Django 3.2.5 on 2021-08-04 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0014_alter_perdaybooking_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perdaybooking',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perdaybooking', to='customers.booking'),
        ),
    ]
