# Generated by Django 3.2.5 on 2021-08-04 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0015_alter_perdaybooking_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
