# Generated by Django 3.2.5 on 2021-08-05 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0016_booking_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perdaybooking',
            name='status',
        ),
    ]
